apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: book-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/bookstore_db"
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: NodePort
  selector:
    app: book-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
