apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-service
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      containers:
        - name: shop-service
          image: shop-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: BOOK_SERVICE_URL
              value: "http://book-service:8081/books"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/bookstore_db"
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  type: NodePort
  selector:
    app: shop-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30002
